14-increment
ChristinaFomenko/URLShortener pull request #5
Opened 2022-07-20 12:55 UTC by ChristinaFomenko

2022-07-21 15:55 UTC, sergeysergeevru requested changes
Привет) Выглядит отлично. Жду завершения имплементации с полными зелеными тестами)

2022-07-21 15:55 UTC, sergeysergeevru commented on internal/app/repository/urls/database/database.go
> +func (r *pgRepo) bindingExists(ctx context.Context, urlID, userID string) (bool, error) {
метод вроде нигде не используется

2022-07-21 15:55 UTC, sergeysergeevru commented on internal/app/repository/urls/database/schema.go
> +	is_deleted     bool default false
можно одним deleted_at маркировать, так как если поле не null то явно запись удалена

2022-07-21 15:55 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	}
в таком случае воркер пул имеет смысл запускать на старте приложения так как практической ценности запуска нескольких горутин на прием для приема одного сообщения из канала нет.

2022-07-21 15:55 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +			_ = h.service.DeleteUserURLs(r.Context(), userID, urls)
можно логировать ошибку, чтобы в случае каких либо проблем это можно было бы отловить

2022-08-03 14:26 UTC, ChristinaFomenko commented
Добрый день! Я не представляю, что может быть не так с асинхронностью. Я немного переделала(как по мне выглядит способным для жизни) и все равно не удается вовремя закончить выполнение теста

2022-08-04 11:28 UTC, sergeysergeevru requested changes
Собственно проблему я подсказал в комменте, осталось только добить)

2022-08-04 11:28 UTC, sergeysergeevru commented on internal/app/repository/urls/database/database.go
> +	stmt, err := tx.PrepareContext(ctx, "UPDATE urls SET deleted = TRUE WHERE user_id = $1 AND url = $2")
У тебя нет в сервисе никаких миграций, чтобы создать это поле deleted. Поэтому на тестах вылетает ошибка. В логах все есть)
<img width="1260" alt="Screenshot 2022-08-04 at 3 23 26 PM" src="https://user-images.githubusercontent.com/12248824/182835379-491c6bac-fcea-4d02-b259-f99db32bf75f.png">

2022-08-04 11:28 UTC, sergeysergeevru commented on internal/app/repository/urls/database/database.go
> +	stmt, err := tx.PrepareContext(ctx, "UPDATE urls SET deleted = TRUE WHERE user_id = $1 AND url = $2")
Вероятно локально все работает, потому что ты руками создала поле в таблице.

2022-08-05 11:46 UTC, ChristinaFomenko commented
Я поправила, в логах те ошибки ушли. Но последнюю часть теста все равно не проходит

2022-08-05 13:10 UTC, sergeysergeevru requested changes
После удаления ссылок твой сервис не отвечает 410, а похоже продолжает редиректить. Как минимум в коде не вижу логики отдачи правильного статуса.  
<img width="1212" alt="Screenshot 2022-08-05 at 5 02 17 PM" src="https://user-images.githubusercontent.com/12248824/183083967-bc545dfb-a762-459e-8d80-c250622048db.png">

2022-08-09 11:18 UTC, sergeysergeevru approved these changes
Отлично!

2022-08-09 11:20 UTC, merged